// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRf8L_LFf2gR2Jh4N8UCUbfiMMpuKYCL8',
    appId: '1:916720039702:web:729301c614610865550237',
    messagingSenderId: '916720039702',
    projectId: 'firstapp-d7c19',
    authDomain: 'firstapp-d7c19.firebaseapp.com',
    storageBucket: 'firstapp-d7c19.appspot.com',
    measurementId: 'G-237QP7ZPJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoNxDmg3pD0x7vSntaJfxngy8wLpIsBIE',
    appId: '1:916720039702:android:ddb9a693b1435009550237',
    messagingSenderId: '916720039702',
    projectId: 'firstapp-d7c19',
    storageBucket: 'firstapp-d7c19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQDqDQV9t8nlkzr-KlyVtgvIrItE-RxAI',
    appId: '1:916720039702:ios:de176e30064f46d9550237',
    messagingSenderId: '916720039702',
    projectId: 'firstapp-d7c19',
    storageBucket: 'firstapp-d7c19.appspot.com',
    iosClientId: '916720039702-gmtvt3qemu2dgf3svilaclnklhlrb5k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProj1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQDqDQV9t8nlkzr-KlyVtgvIrItE-RxAI',
    appId: '1:916720039702:ios:d8ea400b65f5d96b550237',
    messagingSenderId: '916720039702',
    projectId: 'firstapp-d7c19',
    storageBucket: 'firstapp-d7c19.appspot.com',
    iosClientId: '916720039702-48c3lr45ovii4u488k3i4f1i6f283gri.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProj1.RunnerTests',
  );
}
